"""
app.py
Streamlit app for ML Assignment 2.

Run locally in VS Code terminal:
    streamlit run app.py

On Streamlit Community Cloud, set the main file path to: app.py
"""

from pathlib import Path

import pandas as pd
import streamlit as st
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    precision_score,
    recall_score,
    roc_auc_score,
)

st.set_page_config(page_title="ML Assignment 2", layout="wide")
st.title("ML Assignment 2 - Classification Model Comparison")
st.caption("Upload the test CSV, pick a model, and view the evaluation metrics.")

BASE_DIR = Path(__file__).resolve().parent
MODEL_DIR = BASE_DIR / "model"
TARGET_COLUMN = "target"

MODEL_FILES = {
    "Logistic Regression": "logistic_regression.joblib",
    "Decision Tree": "decision_tree.joblib",
    "kNN": "knn.joblib",
    "Naive Bayes": "naive_bayes.joblib",
    "Random Forest (Ensemble)": "random_forest.joblib",
}


@st.cache_resource
def load_model(file_name: str):
    import joblib

    return joblib.load(MODEL_DIR / file_name)


uploaded_file = st.file_uploader("Upload test_data.csv", type=["csv"])
model_name = st.selectbox("Select a model", list(MODEL_FILES.keys()))

if uploaded_file is not None:
    data = pd.read_csv(uploaded_file)
    st.subheader("Uploaded data preview")
    st.dataframe(data.head())

    if TARGET_COLUMN not in data.columns:
        st.error("The uploaded CSV must contain a 'target' column.")
    else:
        X = data.drop(columns=[TARGET_COLUMN])
        y = data[TARGET_COLUMN]

        model = load_model(MODEL_FILES[model_name])
        predictions = model.predict(X)
        probabilities = model.predict_proba(X)[:, 1]

        metrics = {
            "Accuracy": accuracy_score(y, predictions),
            "AUC": roc_auc_score(y, probabilities),
            "Precision": precision_score(y, predictions),
            "Recall": recall_score(y, predictions),
            "F1": f1_score(y, predictions),
            "MCC": matthews_corrcoef(y, predictions),
        }

        st.subheader("Evaluation Metrics")
        st.dataframe(pd.DataFrame([metrics]).style.format("{:.4f}"))

        st.subheader("Confusion Matrix")
        cm = confusion_matrix(y, predictions)
        cm_df = pd.DataFrame(
            cm,
            index=["Actual 0", "Actual 1"],
            columns=["Predicted 0", "Predicted 1"],
        )
        st.table(cm_df)

        st.subheader("Classification Report")
        report = classification_report(y, predictions, output_dict=True)
        st.dataframe(pd.DataFrame(report).transpose())
else:
    st.info("Upload the test_data.csv file generated by train_models.py to see results.")
